local T = require("testlib")
local Stubs = require("wow_stubs")
local describe, it = T.describe, T.it

describe("defaults", function()
    it("returns the default while nothing is stored", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login()
        T.eq(ns.Options:Get("sellJunk"), true)
        T.eq(ns.Options:Get("autoRepair"), false)
        T.eq(ns.Options:Get("guildRepair"), false)
        T.eq(ns.Options:Get("tooltipIDs"), false)
        T.eq(ns.Options:Get("tooltipSellPrice"), true)
        T.eq(ns.Options:Get("hideMicroMenu"), false)
        T.eq(ns.Options:Get("viewportColor"), "ff000000")
    end)

    it("has a false default for every action bar flip", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login()
        for _, bar in ipairs(ns.ActionBars.BARS) do
            T.eq(ns.Options:Get(ns.ActionBars.VerticalKey(bar.frame)), false, bar.frame)
            T.eq(ns.Options:Get(ns.ActionBars.HorizontalKey(bar.frame)), false, bar.frame)
        end
    end)

    it("keeps saved choices across a reload", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login({ hideBagsBar = true, viewportTop = 40 })
        T.eq(ns.Options:Get("hideBagsBar"), true)
        T.eq(ns.Options:Get("viewportTop"), 40)
    end)
end)

describe("Set", function()
    it("stores a value equal to the default as nil", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login()
        ns.Options:Set("sellJunk", false)
        T.eq(QoLDB.options.sellJunk, false)
        ns.Options:Set("sellJunk", true)
        T.eq(QoLDB.options.sellJunk, nil)
    end)

    it("tells watchers about real changes to their keys only", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login()
        local calls = {}
        ns.Options:Watch({ "hideBagsBar" }, function(key, value) calls[#calls + 1] = key .. "=" .. tostring(value) end)
        ns.Options:Set("hideBagsBar", true)
        ns.Options:Set("hideBagsBar", true)
        ns.Options:Set("sellJunk", false)
        T.same(calls, { "hideBagsBar=true" })
    end)

    it("accepts a key predicate for watchers", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login()
        local seen = {}
        ns.Options:Watch(function(key) return key:find("^flip") ~= nil end, function(key) seen[#seen + 1] = key end)
        ns.Options:Set("flipVertical_MainActionBar", true)
        ns.Options:Set("hideBagsBar", true)
        T.same(seen, { "flipVertical_MainActionBar" })
    end)
end)

describe("Init", function()
    it("drops saved values whose type doesn't match the default", function()
        local ns = Stubs.LoadAddon()
        Stubs.Login({ viewportTop = "a lot", hideBagsBar = 1, sellJunk = false })
        T.eq(ns.Options:Get("viewportTop"), 0)
        T.eq(ns.Options:Get("hideBagsBar"), false)
        T.eq(ns.Options:Get("sellJunk"), false)
    end)
end)
